### ISSUE TITLE
Frequent crashes version 0.0.29-15786

### ISSUE THREAD

**Issue by nan0tEch** [RPCS3/rpcs3-binaries-mac#5]
The app crashes when opening the configuration menus on version 0.0.29-15786 mac version running on a macbook pro m1 max. Tried a previous version 0.0.27-14813 the configuration pages opens up.

**Comment by AniLeo** [comment]
This repository does not accept issue tickets.

https://github.com/RPCS3/rpcs3/issues/new/choose
