### ISSUE TITLE
Crash every time with SKATE3

### ISSUE THREAD

**Issue by rebelcode-xr** [RPCS3/rpcs3-binaries-mac#8]
After playing **SKATE3**, when I close the game, the emulator crashes: every single time. However the game is playable, with some visual and sound glitches. I haven't tried other games.

<img width="800" alt="image" src="https://github.com/user-attachments/assets/bb32aa79-11e0-43aa-86ca-e06d4a0d2c49">

> - SYS: RPCS3 v0.0.33-16917-0a54e34a Alpha | HEAD
> - SYS: VirtualApple @ 2.50GHz | 10 Threads | 16.00 GiB RAM | TSC: 1.000GHz
> - SYS: Operating system: macOS, Version: 14.6.1
> - SYS: Current Time: 2024-09-10T12:52:24
> - RSX: Found Vulkan-compatible GPU: 'Apple M1 Pro' running on driver 0.2.994
> - SYS: Firmware version: 4.91

**Comment by AniLeo** [comment]
This repository does not accept issue tickets.

https://github.com/RPCS3/rpcs3/issues/new/choose
